### ISSUE TITLE
Update README with interesting queries and motivation

### ISSUE THREAD

**Issue by costrouc** [Quansight-Labs/python-api-inspect#2]
Some interesting questions that I plan to fill in.

 - [What is the top 10 most popular pandas functions?](https://python-api-inspect.aves.io/inspect-14e1e76?sql=++SELECT+key+AS+function%2C+sum%28json_extract%28value%2C+%27%24.count%27%29%29+as+count%0D%0A++FROM+FunctionStats%2C+json_each%28FunctionStats.stats%29%0D%0A++JOIN+File+ON+FunctionStats.id+%3D+File.id%0D%0A++WHERE+FunctionStats.namespace+%3D+%3Anamespace%0D%0A++++AND+File.filename+NOT+LIKE+%27%25%2Fsite-packages%2F%25%27%0D%0A++++AND+File.filename+LIKE+%27%25.ipynb%27%0D%0A++GROUP+BY+key%0D%0A++ORDER+BY+sum%28json_extract%28value%2C+%27%24.count%27%29%29+desc%0D%0A++LIMIT+10&namespace=pandas)
 - [What is the top 10 most popular numpy attributes?](https://python-api-inspect.aves.io/inspect-14e1e76?sql=++SELECT+key+AS+function%2C+sum%28json_extract%28value%2C+%27%24.count%27%29%29+as+count%0D%0A++FROM+AttributeStats%2C+json_each%28AttributeStats.stats%29%0D%0A++JOIN+File+ON+AttributeStats.id+%3D+File.id%0D%0A++WHERE+AttributeStats.namespace+%3D+%3Anamespace%0D%0A++++AND+File.filename+NOT+LIKE+%27%25%2Fsite-packages%2F%25%27%0D%0A++++AND+File.filename+LIKE+%27%25.ipynb%27%0D%0A++GROUP+BY+key%0D%0A++ORDER+BY+sum%28json_extract%28value%2C+%27%24.count%27%29%29+desc%0D%0A++LIMIT+10&namespace=numpy)
 - What is the are the top 10 most popular stdlib modules used?
 - What are the top 10 least popular stdlib modules used?
 - How are the builtin functions used?
 - Many forms of numpy infinity. Which ones are used the most?
 - How often are the dunder methods used?
 - What are the most popular methods coming from the stdlib?

Any others that people can think of?

**Comment by costrouc** [comment]
README has been updated. https://github.com/Quansight-Labs/python-api-inspect/blob/master/README.md

**Comment by costrouc** [comment]
Keeping PR open for additional questions

**Comment by rgommers** [comment]
Comparing "developer/user communities" would be nice. E.g. "adoption of `pathlib` instead of `os.path` by web devs compared to scientific users". Where the former is defined by use of django/flask, and the latter by use of numpy.
