### ISSUE TITLE
Update scikit-image ipynb csv file

### ISSUE THREAD

**Issue by jni** [Quansight-Labs/python-api-inspect#3]
Hi @costrouc! Would you be able to update the scikit-image csv file for Jupyter notebooks? Here:

https://github.com/Quansight-Labs/python-api-inspect/blob/master/data/csv/scikit-image-summary-notebooks.csv

As you pointed out to me at SciPy, it's empty because the namespace is actually skimage.

Thanks for this awesome work!

**Comment by costrouc** [comment]
Hey @jni it was a pleasure meeting you at SciPy! I have actually stopped using the csv files and instead am now relying on the sqlite sql queries to get results.

Here is a link to the [top 10 functions in scikit-image within notebooks](https://python-api-inspect.aves.io/inspect?sql=++SELECT+key+AS+function%2C+sum%28json_extract%28value%2C+%27%24.count%27%29%29+as+count%0D%0A++FROM+FunctionStats%2C+json_each%28FunctionStats.stats%29%0D%0A++JOIN+File+ON+FunctionStats.id+%3D+File.id%0D%0A++WHERE+FunctionStats.namespace+%3D+%3Anamespace%0D%0A++++AND+File.filename+NOT+LIKE+%27%25%2Fsite-packages%2F%25%27%0D%0A++++AND+File.filename+LIKE+%27%25.ipynb%27%0D%0A++GROUP+BY+key%0D%0A++ORDER+BY+sum%28json_extract%28value%2C+%27%24.count%27%29%29+desc%0D%0A++LIMIT+10&namespace=skimage). Other examples are [here](https://github.com/Quansight-Labs/python-api-inspect#interesting-questions). All the queries can be modified for your specific use case. If you have a query in mind that you need help constructing I am happy to help.

All of this is done with [datasette](https://www.youtube.com/watch?v=lmP75mp3-Rg&t=1601s) which is a read only web server over a sqlite database. This allows for many many more questions to be asked about the data.

**Comment by costrouc** [comment]
There is also a json and csv output that can be produced by datasette

**Comment by jni** [comment]
Thank you @costrouc! My SQL skills are nonexistent, but fiddling with an existing query can get me there. =)

It might still be worth updating the csv file, or removing it, or replacing it with a note, because your original blog post points to it. (Or you could update the blog post!)

**Comment by costrouc** [comment]
Great point. Yeah I have been thinking that this works deserves at least another post or correcting the previous post. I think that the SQL api is much more powerful but as you said it is hard to create a query from scratch. Over time I will add more queries that people can start with.
