### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by amueller** [Quansight-Labs/python-api-inspect#4]
Is the page down? Could you bring it back up? It was quite useful, I think.

**Comment by costrouc** [comment]
Yeup will be bring it back in the next week. I will keep this issue updated with the status

**Comment by amueller** [comment]
Thanks!

**Comment by costrouc** [comment]
A few months later and if forgot to update the issue. The url is back up! Been up for about 3 weeks.

**Comment by costrouc** [comment]
It is now running on a dedicated digital ocean droplet so it should be much more reliable now.

**Comment by amueller** [comment]
awesome, thanks!
